---
name: "Renovate"

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
    inputs:
      dryRun:
        description: "Dry Run"
        default: "false"
        required: false
      logLevel:
        description: "Log Level"
        default: "debug"
        required: false

env:
  LOG_LEVEL: debug
  RENOVATE_DRY_RUN: false
  RENOVATE_CONFIG_FILE: .github/renovate-bot.json5

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.2

      - name: Run Renovate
        uses: renovatebot/github-action@v37.1.0
        with:
          configurationFile: ./github/renovate.json
          token: ${{ secrets.SERVICE_ACCOUNT_TOKEN }}
